version: "3"
services:
    specflow-tests:
        container_name: specflow-tests
        build: .
        depends_on:
        - chrome
    
    chrome:
        image: selenium/standalone-chrome
        ports:
        - "4444:4444"